receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Fluentd Forward receiver for container logs
  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
    check_interval: 5

  # Log-specific processors for structured data
  attributes/logs:
    actions:
      - key: service.name
        action: upsert
        from_attribute: service_name
      - key: service.instance.id
        action: upsert
        from_attribute: instance_name
      - key: trace_id
        action: upsert
        from_attribute: trace_id
      - key: span_id
        action: upsert
        from_attribute: span_id
      - key: pipeline.id
        action: upsert
        from_attribute: pipeline_id
      - key: workitem.id
        action: upsert
        from_attribute: workitem_id
      - key: worker.name
        action: upsert
        from_attribute: worker_name

  resource/logs:
    attributes:
      - key: log.source
        value: fluentd-docker
        action: upsert

exporters:
  # Zipkin
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  # Grafana Tempo
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  # Seq (using OTLP HTTP)
  otlphttp/seq:
    endpoint: "http://seq:5341/ingest/otlp"
    headers:
      "X-Seq-ApiKey": "your-seq-api-key-here"

  # Grafana Loki using HTTP endpoint
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp/v1/logs"
    tls:
      insecure: true

  # Console for debugging
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [zipkin, otlp/tempo, otlphttp/seq]

    logs:
      receivers: [otlp, fluentforward]
      processors: [memory_limiter, resource/logs, attributes/logs, batch]
      exporters: [otlphttp/seq, otlphttp/loki, debug]

    # metrics:
    #   receivers: [otlp]
    #   processors: [memory_limiter, batch]
    #   exporters: [logging]

  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133