version: '3.8'

services:
  # # Main application service
#  ccp:
#    build:
#      context: ./ccp
#      dockerfile: Dockerfile
#    ports:
#      - "5000:8080"
#    depends_on:
#      - redis
#      - rabbitmq
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - Redis__ConnectionString=redis:6379
#      - RabbitMQ__HostName=rabbitmq
#      - RabbitMQ__Port=5672
#      - RabbitMQ__UserName=guest
#      - RabbitMQ__Password=guest
#    networks:
#      - app-network

  # # Worker service
  # worker:
  #   build:
  #     context: ./worker
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Redis__ConnectionString=redis:6379
  #     - RabbitMQ__HostName=rabbitmq
  #     - RabbitMQ__Port=5672
  #     - RabbitMQ__UserName=guest
  #     - RabbitMQ__Password=guest
  #   networks:
  #     - app-network

  # Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
