version: '3.8'

services:
  # CCP Instance 1 - Primary
  ccp-1:
    build:
      context: .
      dockerfile: ccp/Dockerfile
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - INSTANCE_NAME=ccp-1
    networks:
      - app-network

  # CCP Instance 2 - Secondary
  ccp-2:
    build:
      context: .
      dockerfile: ccp/Dockerfile
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - INSTANCE_NAME=ccp-2
    networks:
      - app-network

  # CCP Instance 3 - Tertiary
  ccp-3:
    build:
      context: .
      dockerfile: ccp/Dockerfile
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - INSTANCE_NAME=ccp-3
    networks:
      - app-network

  # nginx Load Balancer (ONLY access point)
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ccp-1
      - ccp-2
      - ccp-3
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  # # Worker service
  # worker:
  #   build:
  #     context: ./worker
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Redis__ConnectionString=redis:6379
  #     - RabbitMQ__HostName=rabbitmq
  #     - RabbitMQ__Port=5672
  #     - RabbitMQ__UserName=guest
  #     - RabbitMQ__Password=guest
  #   networks:
  #     - app-network

volumes:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
